Shang New Live/src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>Roll-up of Amount from related Invoice Line Item</inlineHelpText>
        <label>Amount</label>
        <summarizedField>Invoice_Line_Item__c.Amount__c</summarizedField>
        <summaryForeignKey>Invoice_Line_Item__c.Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Property_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Created this field to manage Misc Invoice Process - to generate PDF</inlineHelpText>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <formula>CASESAFEID(Lease__r.Property__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>from related Lease.
Used in Cash Receipt Interface</inlineHelpText>
        <label>Property ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rent_Roll__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rent Roll</label>
        <referenceTo>Rent_Roll__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Shang New Live/src/objects/Invoice_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>Managed by Invoice Trigger (works on Invoice creation only):
This Amount shows summarized Amount from related RRDs</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <inlineHelpText>Managed by Invoice Trigger to get value from related RRD on Invoice creation</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <formula>Lease_Charge__r.Lease_Unit__r.Unit__r.Unit_No__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unit</label>
        <type>Text</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>{yyyy}-{mm}-RI-{00000000}</displayFormat>
        <label>Invoice Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Shang New Live/src/objects/Lease__c.object
<CustomObject>
    <fields>
        <fullName>Property_Name__c</fullName>
        <formula>Property__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Property Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Leases</relationshipLabel>
        <relationshipName>Leases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rent_Roll__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rent Roll</label>
        <referenceTo>Rent_Roll__c</referenceTo>
        <relationshipLabel>Leases</relationshipLabel>
        <relationshipName>Leases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Lease</label>
    <nameField>
        <label>Lease Agreement No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Shang New Live/src/objects/Lease_Charges__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expected_Amount__c</fullName>
        <description>*Need to check if this is used anywhere*
Does Not appear on Layout</description>
        <label>Expected Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Lease_Unit__c</fullName>
        <label>Lease Unit</label>
        <referenceTo>Lease_Unit__c</referenceTo>
        <relationshipLabel>Lease Charges</relationshipLabel>
        <relationshipName>Lease_Charges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Lease Charge</label>
    <nameField>
        <label>Lease Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lease Charges</pluralLabel>
    <recordTypes>
        <fullName>Rent</fullName>
        <active>true</active>
        <description>Base Rent &amp; GTO</description>
        <label>Rent</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Shang New Live/src/objects/Lease_Unit__c.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <formula>Lease_Agreement_No__r.Property__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Property</label>
        <type>Text</type>
    </fields>
    <label>Lease Unit</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-LU-{00000000}</displayFormat>
        <label>Lease Unit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lease Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Shang New Live/src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Shang New Live/src/objects/Rent_Roll__c.object
<CustomObject>
    <fields>
        <fullName>Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Approved By (Operations Manager)</description>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Rent_Roll</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property_Name__c</fullName>
        <formula>Property__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Property Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Rent Roll</relationshipLabel>
        <relationshipName>Rent_Roll</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rent_Roll_Date__c</fullName>
        <label>Rent Roll Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Diesel_Rate__c</fullName>
        <description>Total Diesel Rate for the Month.</description>
        <inlineHelpText>Total Diesel Rate for the Month.</inlineHelpText>
        <label>Total Diesel Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Leased_Area_Sq_Ft__c</fullName>
        <label>Total Leased Area (Sq. Ft.)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Rent Roll</label>
    <nameField>
        <label>Rent Roll ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rent Roll</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Shang New Live/src/objects/Rent_Roll_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Billing_Date__c</fullName>
        <label>Billing Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expected_Amount__c</fullName>
        <label>Expected Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Hold__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hold</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lease_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lease Unit</label>
        <referenceTo>Lease_Unit__c</referenceTo>
        <relationshipLabel>Rent Roll Details</relationshipLabel>
        <relationshipName>Rent_Roll_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <formula>Unit__r.Property__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Property</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rent_Roll__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rent Roll</label>
        <referenceTo>Rent_Roll__c</referenceTo>
        <relationshipLabel>Rent Roll Details</relationshipLabel>
        <relationshipName>Rent_Roll_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Rent Roll Detail</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-RRD-{000000}</displayFormat>
        <label>RRD ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rent Roll Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Shang New Live/src/objects/Rent_Schedules__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Billing_Date__c</fullName>
        <label>Billing Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expected_Amount__c</fullName>
        <label>Expected Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Hold__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hold</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lease_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lease Unit</label>
        <referenceTo>Lease_Unit__c</referenceTo>
        <relationshipLabel>Rent Schedules</relationshipLabel>
        <relationshipName>Rent_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <formula>Unit__r.Property__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>from related Unit</inlineHelpText>
        <label>Unit Property</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rent_Roll__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rent Roll</label>
        <referenceTo>Rent_Roll__c</referenceTo>
        <relationshipLabel>Rent Schedules</relationshipLabel>
        <relationshipName>Rent_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Rent Schedule</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-RS-{00000000}</displayFormat>
        <label>Rent Schedule No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rent Schedules</pluralLabel>
    <recordTypes>
        <fullName>Rent</fullName>
        <active>true</active>
        <description>Base Rent &amp; GTO</description>
        <label>Rent</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Shang New Live/src/objects/Units__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Units</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Unit</label>
    <nameField>
        <label>Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Shang New Live/src/classes/ApproveRentScheduleController.cls
public class ApproveRentScheduleController{
    /*public Rent_Roll__c rentRoll{get;set;}
    public List<Rent_Roll__c> rentRollList{get;set;}
    public string status{get;set;}
    public string selRentRollId{get;set;}
    public Boolean showRentDetail{get;set;}
    public Boolean selectAll{get;set;}
    public List<Rent_Schedules__c> rentScheduleList{get;set;}
    
    public List<Rent_Roll__c> displayRentRolLList{get;set;}
    public Boolean isrrNext{get;set;}
    public Boolean isrrPrev{get;set;}
    public Integer rrPageSize{get;set;}
    public Integer rrRecordCount{get;set;}
    public ApproveRentScheduleController(){
        rrPageSize = 10;
        isrrPrev = false;
        isrrNext = false;
        rrRecordCount = 0;
        displayRentRolLList = new List<Rent_Roll__c>();
        
        rentRoll = new Rent_Roll__c();
        rentRollList = new List<Rent_Roll__c>();        
        status = 'Approved';
        showRentDetail = false;
        selectAll = false;
        rentScheduleList = new List<Rent_Schedules__c>();
    }
    
    public void search(){
        rentRollList = new List<Rent_Roll__c>();
        displayRentRolLList = new List<Rent_Roll__c>();
        if(rentRoll.Property__c!=null){
            string query = 'Select id,Name,Property_Name__c,Rent_Roll_Date__c,Approved__c,Property__c,Approver__c,Total_Diesel_Rate__c,Total_Leased_Area_Sq_Ft__c,(Select id,Name,Active__c,Billing_Date__c,End_Date__c,Expected_Amount__c,Hold__c,Lease_Unit__c,Rent_Roll__c,Start_Date__c,Status__c,Total_Units_p__c,Trading_Day_s__c,Unit__c,Approved__c,Tenant__c,Unit__r.Name,Lease_Charge__r.Name,Total_Units__c,Lease_Charge__r.Charge_Rate__c,Amount__c,Lease_Charge__c,Lease_Unit__r.Lease_Agreement_No__c,Lease_Charge__r.Charge_Description__c from Rent_Schedules__r where Approved__c=false) from Rent_Roll__c where Property__c=\''+rentRoll.Property__c+'\'';
            if(status=='Approved'){            
                query += ' and Approved__c=true';
            }else if(Status=='Pending Approval'){
                query += ' and Approved__c=false';
            }
            
            query += ' limit 1000';
            
            for(Rent_Roll__c rr:database.query(query)){
                if(rr.Rent_Schedules__r.size()>0){
                    rentRollList.add(rr);
                }
            }
            
            if(rentRollList.size()>rrPageSize){
                isrrNext = true;
                for(Integer i=0;i<rrPageSize;i++){
                    displayrentRollList.add(rentRollList[i]);
                }
                rrRecordCount = rrPageSize;
            }else{
                displayrentRollList = rentRollList;
            }
        }
    }
    
    public void rrNext(){
        displayRentRolLList = new List<Rent_Roll__c>();
        Integer maxCount = rrRecordCount + rrPageSize;
        if(maxCount>rentRollList.size()){
            maxCount = rentRollList.size();
        }
        for(Integer i=rrRecordCount;i<maxcount;i++){
            displayRentRollList.add(rentRollList[i]);
        }
        rrRecordCount = maxCount;
        isrrPrev= true;
        if(rrRecordCount==rentRollList.size()){
            isrrNext = false;
        }
        
    }
    
    public void rrPrevious(){
        displayRentRolLList = new List<Rent_Roll__c>();
        if(rrRecordCount==rentRollList.size()){
            rrRecordCount = rrRecordCount - (Math.mod(rrRecordCount,rrPageSize)>0?Math.mod(rrRecordCount,rrPageSize):rrPageSize);
        }else{
            rrRecordCount = rrRecordCount - rrPageSize;
        }
        Integer minCount = rrRecordCount - rrPageSize;
        for(Integer i=rrRecordCount-1;i>=mincount;i--){
            displayRentRollList.add(rentRollList[i]);
        }
        isrrNext = true;
        if(rrRecordCount==rrPageSize){
            isrrPrev = false;
        }
    }
    
    public void selectRentRoll(){
        rentScheduleList = new List<Rent_Schedules__c>();
        if(selRentRollId!=null){
            for(rent_Roll__c rr:rentRollList){
                if(rr.Id==selRentRollId){
                    rentRoll = rr;
                    showRentDetail = true;
                    rentScheduleList = rr.Rent_Schedules__r;
                    break;
                }
            }
        }
    }
    
    public void selectAllToApprove(){
        for(Rent_Schedules__c rs:rentScheduleList){
            rs.Approved__c = selectAll;
        }
    }
    
    public pageReference approve(){
        if(rentRoll.Id!=null){
            if(rentScheduleList.size()>0){
                Boolean apprCheck = false;
                List<Rent_Roll_Detail__c> rrDetailList = new List<Rent_Roll_Detail__c>();
                for(Rent_Schedules__c rs:rentScheduleList){
                    if(rs.Approved__c){
                        apprCheck = true;
                        
                        Rent_Roll_Detail__c rrDet = new Rent_Roll_Detail__c();
                        rrDet.Name = rs.Name;
                        rrDet.Active__c = rs.Active__c;
                        rrDet.Amount__c = rs.Amount__c;
                        rrDet.Approved__c = rs.Approved__c;
                        rrDet.Billing_Date__c = rs.Billing_Date__c;
                        rrDet.End_Date__c = rs.End_Date__c;
                        rrDet.Lease_Charge__c = rs.Lease_Charge__c;
                        rrDet.Lease_Unit__c = rs.Lease_Unit__c;
                        rrDet.Rent_Roll__c = rs.Rent_Roll__c;
                        rrDet.Start_Date__c = rs.Start_Date__c;
                        rrDet.Status__c = rs.Status__c;
                        rrDet.Total_Units_p__c = rs.Total_Units_p__c;
                        rrDet.Trading_Day_s__c = rs.Trading_Day_s__c;
                        rrDet.Unit__c = rs.Unit__c;
                        rrDetailList.add(rrDet);
                    }
                }
                if(!apprCheck){
                    Apexpages.addMessage(new apexpages.message(Apexpages.Severity.Error,'Please check atleast 1 Rent Schedule.'));
                    return null;
                }
                update rentScheduleList;
                insert rrDetailList;
                
                Invoice__c inv = new Invoice__c();
                inv.Rent_Roll__c = rentRoll.Id;
                inv.Status__c = 'Ready';
                inv.Invoice_Date__c = rentRoll.Rent_Roll_Date__c;
                if(rentRoll.Rent_Roll_Date__c!=null){
                    inv.Payment_Due_Date__c = rentRoll.Rent_Roll_Date__c.addMonths(1);
                }
                inv.Invoice_Type__c = 'System Generated Invoice';
                inv.Name = 'INV-'+rentRoll.Property_Name__c+'-'+rentScheduleList[0].Tenant__c+'-'+rentRoll.Rent_Roll_Date__c.format(); 
                inv.Lease__c = rentScheduleList[0].Lease_Unit__r.Lease_Agreement_No__c;
                insert inv;
                List<Invoice_Line_Item__c> lineItmList = new List<Invoice_Line_Item__c>();
                for(Rent_Schedules__c rs:rentScheduleList){
                    if(rs.Approved__c){
                        Invoice_Line_Item__c invLinItm = new Invoice_Line_Item__c();
                        invLinItm.Rent_Schedule__c = rs.Id;
                        invLinItm.Description__c = rs.Lease_Charge__r.Charge_Description__c;
                        invLinItm.Amount__c = rs.Amount__c;
                        invLinItm.Invoice__c = inv.Id;
                        lineItmList.add(invLinItm);
                    }
                }
                insert lineItmList;
                return new pageReference('/'+inv.Id);
            }else{
                Apexpages.addMessage(new apexpages.message(Apexpages.Severity.Error,'Rent Schedules not found.'));
            }
        }else{
            Apexpages.addMessage(new apexpages.message(Apexpages.Severity.Error,'Rent Roll not found.'));
        }
        return null;
    }
    
    public void save(){
        update rentRoll;
        rentScheduleList = [Select id,Approved__c,Tenant__c,Unit__r.Name,Lease_Charge__r.Name,Total_Units__c,Lease_Charge__r.Charge_Rate__c,Amount__c,Lease_Charge__c,Lease_Unit__r.Lease_Agreement_No__c,Lease_Charge__r.Charge_Description__c from Rent_Schedules__c where Rent_Roll__c=:rentRoll.Id and Approved__c=false];
    }*/
}