Shang New Live/src/objects/Lease__c.object
<CustomObject>
    <fields>
        <fullName>Lease_End_Date__c</fullName>
        <formula>IF(ISBLANK(TEXT(Lease_Tenure_Days__c)),0,+ VALUE(TEXT(Lease_Tenure_Days__c))) 
+ 
(DATE( 
YEAR( Lease_Start_Date__c ) + FLOOR( ( MONTH ( Lease_Start_Date__c ) + Lease_Tenure_Mths__c - 1 ) / 12 ), 
MOD( MONTH ( Lease_Start_Date__c ) + Lease_Tenure_Mths__c - 1 + 
IF( DAY ( Lease_Start_Date__c ) &gt; CASE( MOD( MONTH( Lease_Start_Date__c ) + Lease_Tenure_Mths__c - 1, 12 ) + 1, 
2, 28, 
4, 30, 
6, 30, 
9, 30, 
11, 30, 
31 ), 1, 0 ), 12 ) + 1, 
IF( DAY( Lease_Start_Date__c ) &gt; CASE( MOD( MONTH( Lease_Start_Date__c) + Lease_Tenure_Mths__c - 1, 12 ) + 1, 
2, 28, 
4, 30, 
6, 30, 
9, 30, 
11, 30, 
31 ), 
1, DAY( Lease_Start_Date__c ) 
) 
)-1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Original End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lease_Start_Date__c</fullName>
        <label>Lease Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lease_Status__c</fullName>
        <description>Status of the Lease
New = New lease
Cancel = Cancel a lease
Renewal = Lease is renewed
Expire = Lease has expired with no renewal
Pre-Term = Lease has pre-terminated</description>
        <inlineHelpText>Lease status of the LA
New = New lease
Cancel = Cancel a lease
Renewal = Lease is renewed
Expire = Lease has expired with no renewal
Pre-Term = Lease has pre-terminated</inlineHelpText>
        <label>Lease Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Renewed</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Pre-Terminated</fullName>
                </value>
                <value>
                    <fullName>Extended</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Original_End_Date__c</fullName>
        <inlineHelpText>This field would be populated only in the case of Extension or Pre-Termination and would show the Revised End Date as per Extension or Pre-Termination.</inlineHelpText>
        <label>Revised End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Pre_Terminated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pre-Terminated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reason_for_Termination__c</fullName>
        <label>Reason for Termination</label>
        <type>TextArea</type>
    </fields>
    <label>Lease</label>
    <nameField>
        <label>Lease Agreement No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Shang New Live/src/objects/Lease_Charges__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lease_Status__c</fullName>
        <formula>TEXT(Lease_Unit__r.Lease_Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Lease Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lease_Unit__c</fullName>
        <label>Lease Unit</label>
        <referenceTo>Lease_Unit__c</referenceTo>
        <relationshipLabel>Lease Charges</relationshipLabel>
        <relationshipName>Lease_Charges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Pre_Termination__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pre Termination</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Lease Charge</label>
    <nameField>
        <label>Lease Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lease Charges</pluralLabel>
    <recordTypes>
        <fullName>Rent</fullName>
        <active>true</active>
        <description>Base Rent &amp; GTO</description>
        <label>Rent</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Shang New Live/src/objects/Lease_Unit__c.object
<CustomObject>
    <fields>
        <fullName>Lease_Agreement_No__c</fullName>
        <label>Lease Agreement No.</label>
        <referenceTo>Lease__c</referenceTo>
        <relationshipLabel>Lease Units</relationshipLabel>
        <relationshipName>Lease_Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Lease_End_Date__c</fullName>
        <label>Lease End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lease_Start_Date__c</fullName>
        <label>Lease Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lease_Status__c</fullName>
        <label>Lease Unit Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Renewed</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Pre-Terminated</fullName>
                </value>
                <value>
                    <fullName>Extended</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Replaced</fullName>
                </value>
                <value>
                    <fullName>Vacant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Original_End_Date__c</fullName>
        <inlineHelpText>This field would be populated only in the case of Extension or Pre-Termination and would show the Original End Date of this Lease Unit.</inlineHelpText>
        <label>Original End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Pre_Terminated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pre-Terminated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pre_Termination__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pre-Termination</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reason_for_Termination__c</fullName>
        <label>Reason for Termination</label>
        <type>TextArea</type>
    </fields>
    <label>Lease Unit</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-LU-{00000000}</displayFormat>
        <label>Lease Unit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lease Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Shang New Live/src/objects/Rent_Schedules__c.object
<CustomObject>
    <fields>
        <fullName>Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lease_Agreement_No__c</fullName>
        <formula>Lease_Unit__r.Lease_Agreement_No__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>from related Lease Unit</inlineHelpText>
        <label>Lease Agreement No.</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lease_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lease Unit</label>
        <referenceTo>Lease_Unit__c</referenceTo>
        <relationshipLabel>Rent Schedules</relationshipLabel>
        <relationshipName>Rent_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Vacancy</fullName>
                </value>
                <value>
                    <fullName>In-Tenancy</fullName>
                </value>
                <value>
                    <fullName>Rent Roll Generated</fullName>
                </value>
                <value>
                    <fullName>Payment Received</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Rent Free</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Rent Schedule</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-RS-{00000000}</displayFormat>
        <label>Rent Schedule No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rent Schedules</pluralLabel>
    <recordTypes>
        <fullName>Rent</fullName>
        <active>true</active>
        <description>Base Rent &amp; GTO</description>
        <label>Rent</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Shang New Live/src/classes/PreTerminateLease_Extension.cls
/*
    Name    :   PreTerminateLease_Extension
    Author  :   Arshad Shaikh (Techmatrix Consulting)
    Date    :   09/01/2017
    Description : This extension is used in  is used for PreTerminateLease Page.
            To Pre terminate Lease, Lease Unit, Rent Schedule and Lease Charges according to date input by user.
    Test Class: PreTerminate_Test
*/
public class PreTerminateLease_Extension {
    public Lease__c leaseOnUI{get;set;}
    public Boolean error{get;set;}
    public Boolean termError{get;set;}
    public String dtString{get;set;}
    public Boolean closePage{get;set;}
    public String selectedLease{get;set;}
    String currentEndDate{get;set;}
    Date EndDate{get;set;}
    public PreTerminateLease_Extension(ApexPages.StandardController stdController) {
        this.leaseOnUI = (Lease__c) stdController.getRecord();
        leaseOnUI.Lease_Start_Date__c = System.today();
        currentEndDate = ApexPages.currentpage().getParameters().get('endDate');
        selectedLease = ApexPages.currentpage().getParameters().get('selectedLease');

        if (currentEndDate != null && currentEndDate != '') {
            EndDate = date.parse(currentEndDate);
        }
    }

    public void checkDate() {
        SavePoint sp = Database.setSavePoint();
        error = false;
        termError = false;
        Lease__c lc = [select Id, Lease_Status__c,Pre_Terminated__c, Original_End_Date__c, Lease_Start_Date__c, Reason_for_Termination__c from Lease__c where Id =: selectedLease];

        if (leaseOnUI.Reason_for_Termination__c == null || leaseOnUI.Reason_for_Termination__c.trim() == '') {
            termError = true;
            error = true;
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, 'Please add Reason for Termination'));
        }
        System.debug('leaseOnUI.Lease_Start_Date__c-->' + leaseOnUI.Lease_Start_Date__c);
        System.debug('EndDate-->' + EndDate);
        System.debug('(leaseOnUI.Lease_Start_Date__c > EndDate )-->' + (leaseOnUI.Lease_Start_Date__c > EndDate));
        if (leaseOnUI.Lease_Start_Date__c == null) {
            error = true;
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, 'Please Select Termination Date'));
        } else if (leaseOnUI.Lease_Start_Date__c <= lc.Lease_Start_Date__c) {
            error = true;
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, 'Pre-Termination Date must be after Lease Start Date.'));
        } else if (leaseOnUI.Lease_Start_Date__c > EndDate) {
            error = true;
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, 'Pre-Termination Date must be before Revised End Date.'));
        } else {
            error = false;
            dtString = DateTime.newInstance(leaseOnUI.Lease_Start_Date__c.year(), leaseOnUI.Lease_Start_Date__c.month(), leaseOnUI.Lease_Start_Date__c.day()).format('YYYY/MM/d');
        }
        if (!error && !termError) {
            closePage = true;
            System.debug('lc--->' + lc);
            //lc.Lease_Status__c = 'Pre-Terminated';
            lc.Pre_Terminated__c = true;
            lc.Reason_for_Termination__c = leaseOnUI.Reason_for_Termination__c;
            lc.Original_End_Date__c = leaseOnUI.Lease_Start_Date__c;

            List < Lease_Unit__c > luList = [Select Id, Name, Original_End_Date__c,Pre_Termination__c, Lease_Start_Date__c, Lease_End_Date__c, Lease_Agreement_No__r.Lease_Start_Date__c, Lease_Agreement_No__r.Original_End_Date__c from Lease_Unit__c where Lease_Agreement_No__r.Id =: selectedLease];
            List < Rent_Schedules__c > rsList = new List < Rent_Schedules__c >();
            List < Lease_Charges__c > lcList = new List < Lease_Charges__c >();
            Set < Id > luIds = new Set < Id > ();
            if (luList.size() > 0) {
                try {
                    for (Lease_Unit__c lu: luList) {
                        if (lu.Lease_End_Date__c > leaseOnUI.Lease_Start_Date__c) {
                            lu.Pre_Termination__c = true;
                            lu.Reason_for_Termination__c = leaseOnUI.Reason_for_Termination__c;
                            //lu.Lease_Start_Date__c = lu.Lease_Agreement_No__r.Lease_Start_Date__c;
                            lu.Lease_End_Date__c = leaseOnUI.Lease_Start_Date__c;
                        }
                        luIds.add(lu.Id);
                    }
                    rsList = [Select Id, Status__c, Start_Date__c, End_Date__c, Lease_Unit__c, Lease_Unit__r.Lease_Start_Date__c, Lease_Unit__r.Lease_End_Date__c, Lease_Unit__r.Lease_Agreement_No__r.Lease_Start_Date__c, Lease_Unit__r.Lease_Agreement_No__r.Original_End_Date__c from Rent_Schedules__c where Lease_Unit__c =: luIds];
                    if (rsList.size() > 0) {
                        for (Rent_Schedules__c rs: rsList) {
                            if(rs.Status__c == 'Rent Roll Generated' && rs.Start_Date__c >= leaseOnUI.Lease_Start_Date__c && rs.End_Date__c >= leaseOnUI.Lease_Start_Date__c){
                                error = true;
                                closePage = false;
                                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'Rent Roll already generated for this Lease and cannot be Terminated.'));
                            }else if (rs.Start_Date__c > leaseOnUI.Lease_Start_Date__c) {
                                rs.Status__c = 'Terminated';
                                rs.Approved__c = true;
                            } else if (rs.Start_Date__c < leaseOnUI.Lease_Start_Date__c && rs.End_Date__c > leaseOnUI.Lease_Start_Date__c) {
                                rs.End_Date__c = leaseOnUI.Lease_Start_Date__c;
                            }
                        }
                    }
                    lcList = [Select Id, Start_Date__c,Pre_Termination__c, End_Date__c, Lease_Unit__c, Lease_Unit__r.Lease_Start_Date__c, Lease_Unit__r.Lease_End_Date__c, Lease_Unit__r.Lease_Agreement_No__r.Lease_Start_Date__c, Lease_Unit__r.Lease_Agreement_No__r.Original_End_Date__c from Lease_Charges__c where Lease_Unit__c =: luIds];
                    if (lcList.size() > 0) {
                        for (Lease_Charges__c lcl: lcList) {
                            lcl.Pre_Termination__c = true;
                            if (lcl.End_Date__c > leaseOnUI.Lease_Start_Date__c && lcl.Start_Date__c < leaseOnUI.Lease_Start_Date__c) {
                                lcl.End_Date__c = leaseOnUI.Lease_Start_Date__c;
                            }
                        }
                    }

                } catch (Exception e) {
                    closePage = false;
                    error = true;
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, 'Exception Occured- ' + e));
                }
            }
            if(!error){
                try {
                    update lc;
                    update luList;
                    //update rsList;
                    update lcList;
                } catch (Exception e) {
                    Database.rollback(sp);
                    closePage = false;
                    error = true;
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, 'Exception Occured- ' + e));
                }
            }

        }
    }
}