WindGroup Dev/src/objects/COA_FY_Balance__c.object
<CustomObject>
    <fields>
        <fullName>Budget_Amount__c</fullName>
        <label>Budget Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Budget_Line__c</fullName>
        <formula>TEXT ( Operational_Budget__r.Budget_Line__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Budget Line</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <formula>TEXT( Operational_Budget__r.Department__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Department</label>
        <type>Text</type>
    </fields>
    <label>COA FY Balance</label>
    <nameField>
        <displayFormat>COA Bal-{000000}</displayFormat>
        <label>COA Bal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>COA FY Balance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WindGroup Dev/src/objects/Goods_Receipt__c.object
<CustomObject>
    <fields>
        <fullName>Currency_Code__c</fullName>
        <label>Currency Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Currency_Code</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <label>PO No.</label>
        <referenceTo>Purchase_Order__c</referenceTo>
        <relationshipLabel>Goods Receipts</relationshipLabel>
        <relationshipName>Goods_Receipts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Vendor_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Goods Receipts</relationshipLabel>
        <relationshipName>Goods_Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Goods Receipt</label>
    <nameField>
        <label>Goods Receipt No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goods Receipts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WindGroup Dev/src/objects/GR_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Budget_Line__c</fullName>
        <label>Budget Line</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Lift</fullName>
                </value>
                <value>
                    <fullName>Pump</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Currency_Code__c</fullName>
        <label>Currency Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Currency_Code</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PO_Line_Item__c</fullName>
        <label>PO Line Item</label>
        <referenceTo>PO_Line_Item__c</referenceTo>
        <relationshipLabel>GR Line Items</relationshipLabel>
        <relationshipName>GR_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>GR Line Item</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-GRI-{000000}</displayFormat>
        <label>GR Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GR Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WindGroup Dev/src/objects/Item_Catalogue__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Department</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&quot;Active&quot;</defaultValue>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Replaced</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vendor_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Item_Catalogues</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Catalogue</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Catalogue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WindGroup Dev/src/objects/PO_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Budget_Line__c</fullName>
        <label>Budget Line</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Budget_Line</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>COA_FY_Balance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>COA FY Balance</label>
        <referenceTo>COA_FY_Balance__c</referenceTo>
        <relationshipLabel>PO Line Items</relationshipLabel>
        <relationshipName>PO_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Currency_Code__c</fullName>
        <formula>TEXT(Purchase_Order__r.Currency_Code__c)</formula>
        <label>Currency Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <formula>TEXT(Purchase_Order__r.Department__c)</formula>
        <label>Department</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Catalogue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Catalogue</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Item_Catalogue__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Item_Catalogue__c</referenceTo>
        <relationshipLabel>PO Line Items</relationshipLabel>
        <relationshipName>PO_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <label>PO No.</label>
        <referenceTo>Purchase_Order__c</referenceTo>
        <relationshipLabel>PO Line Items</relationshipLabel>
        <relationshipName>PO_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>PO Line Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PO Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WindGroup Dev/src/objects/PO_Payment_Arrangement__c.object
<CustomObject>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Purchase Order</label>
        <referenceTo>Purchase_Order__c</referenceTo>
        <relationshipName>PO_Payment_Terms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>PO Payment Arrangement</relationshipLabel>
        <relationshipName>PO_Payment_Arrangement</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PO Payment Arrangement</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>PO PT ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PO Payment Arrangement</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WindGroup Dev/src/objects/Purchase_Order__c.object
<CustomObject>
    <fields>
        <fullName>Currency_Code__c</fullName>
        <label>Currency Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Currency_Code</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Department</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Generate_PO_PDF__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Generate PO PDF</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PO_End_Date__c</fullName>
        <label>Expected Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PO_Line_Validation_Bypass__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox is used to bypass PO Line Item validation rule</description>
        <label>PO Line Validation Bypass</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PO_Start_Date__c</fullName>
        <label>PO Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In-Approval</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Issued</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Cancel In-Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vendor_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Whitelisted__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Purchase Orders (Vendor Name)</relationshipLabel>
        <relationshipName>Purchase_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>X3_Quotes__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select this and attach 3 Quotes</inlineHelpText>
        <label>3 Quotes</label>
        <type>Checkbox</type>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <label>PO No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WindGroup Dev/src/classes/ManageInventoryTriggerTest.cls
@isTest
public class ManageInventoryTriggerTest   {
    @isTest
    static void test1(){
        Account ac1=new Account();
        ac1.RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Vendor').getRecordTypeId();
        ac1.Name='testAc1';
        insert ac1;
        
        Account ac2=new Account();
        ac2.RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Vendor').getRecordTypeId();
        ac2.Name='testAc1';
        insert ac2;
        
        Property__c prop = new Property__c();
        prop.Name = 'TestProperty';
        insert prop;
        
        Purchase_Order__c po=new Purchase_Order__c();
        po.PO_Start_Date__c=date.today();
        po.Status__c='Draft';
        po.PO_End_Date__c=date.today()+30;
        po.Currency_Code__c=label.Default_Currency;
        po.X3_Quotes__c = true;
        po.PO_Line_Validation_Bypass__c = false;
        po.Generate_PO_PDF__c=false;
        po.Vendor_Name__c=ac1.id;
        po.Property__c = prop.Id;
        insert po;
        
        COA_FY_Balance__c cb=new COA_FY_Balance__c();
        cb.Budget_Amount__c=3000;
        insert cb;
        
        Item_Catalogue__c ic = new Item_Catalogue__c();
        ic.Name = 'TestPrd';
        ic.Amount__c = 10;
        ic.Department__c = 'Operations';
        ic.Expiry_Date__c = system.today().addDays(2);
        ic.Product_Name__c = 'TestPrd';
        ic.Product_Type__c = 'Equipment';
        ic.Status__c = 'Active';
        ic.Vendor_Name__c = ac1.Id;
        insert ic;
        
        
        PO_Line_Item__c pol=new PO_Line_Item__c();
        pol.Amount__c=2000;
        pol.COA_FY_Balance__c=cb.Id;
        pol.Purchase_Order__c=po.Id;
        pol.Budget_Line__c='Hardware Maintenance';
        pol.Quantity__c=1;
        pol.Product_Type__c = 'Equipment';
        pol.Product_Catalogue__c = ic.Id;
        insert pol;
        
        
        
        
        PO_Payment_Arrangement__c pa=new PO_Payment_Arrangement__c();
        pa.Purchase_Order__c=po.Id;
        insert pa;
        
        
        po.PO_Line_Validation_Bypass__c = true;
        po.Status__c='Issued';
        update po;
        
        
        
        Goods_Receipt__c gr=new Goods_Receipt__c();
        gr.Purchase_Order__c=po.Id;
        //gr.Vendor_Name__c=ac.Id;
        insert gr;
        
        GR_Line_Item__c gri=new GR_Line_Item__c();
        gri.PO_Line_Item__c=pol.Id;
        gri.Goods_Receipt__c=gr.Id;
        gri.Quantity__c = 1;
        insert gri;
        
    }
}