WindGroup Dev/src/objects/Electric_Meter__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Meter_No__c</fullName>
        <label>Meter No</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <formula>Unit__r.Property__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Property</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit</label>
        <referenceTo>Units__c</referenceTo>
        <relationshipName>Electric_Meter_No</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Electric Meter</label>
    <nameField>
        <displayFormat>{yyyy}-{mm}-EM-{00000000}</displayFormat>
        <label>Electric Meter Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Electric Meter</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

WindGroup Dev/src/objects/Level__c.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Levels</relationshipLabel>
        <relationshipName>Levels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Level</label>
    <nameField>
        <label>Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Levels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WindGroup Dev/src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

WindGroup Dev/src/objects/Units__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Level</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Property__c</field>
                <operation>equals</operation>
                <valueField>Level__c.Property__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Level__c</referenceTo>
        <relationshipLabel>Units</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Units</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Unit</label>
    <nameField>
        <label>Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WindGroup Dev/src/classes/MainMeterTrigger_Test.cls
@isTest(seeAllData=false)
public with sharing class MainMeterTrigger_Test {
	static Property__c prop;
	static Level__c lvl;
	static Units__c unt;
    static void init(){
		prop = new Property__c();
        prop.Name = 'TestProperty';
        insert prop;
        
        lvl = new Level__c();
        lvl.Name = 'TestLevel';
        lvl.Property__c = prop.Id;
        insert lvl;
        
        unt = new Units__c();
        unt.Property__c = prop.Id;
        unt.Level__c = lvl.Id;
        unt.Name = 'TestUnit';
        unt.Active__c = true;
        unt.Start_Date__c = system.today();
        unt.End_Date__c = system.today().addYears(2);
        unt.Active__c = true;
        insert unt;
    }
    static testMethod void runInserRS1() {
		init();
		Test.startTest();
			Electric_Meter__c emc1= new Electric_Meter__c();
			emc1.Status__c = 'Inactive';
			emc1.Meter_No__c = 'Meter1';
			emc1.Unit__c = unt.Id;
			insert emc1;
			
			
			Electric_Meter__c emc= new Electric_Meter__c();
			emc.Status__c = 'Active';
			emc.Meter_No__c = 'Meter1';
			emc.Unit__c = unt.Id;
			insert emc;
			
		Test.stopTest();
	}		
}