WindGroup Dev/src/objects/Electric_Meter__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Meter_No__c</fullName>
        <label>Meter No</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Meter_Type__c</fullName>
        <label>Meter Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Meter_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Remarks__c</fullName>
        <label>Remarks</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit</label>
        <referenceTo>Units__c</referenceTo>
        <relationshipName>Electric_Meter_No</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Electric Meter</label>
    <nameField>
        <displayFormat>{yyyy}-{mm}-EM-{00000000}</displayFormat>
        <label>Electric Meter Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Electric Meter</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

WindGroup Dev/src/objects/Electric_Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Electric_Meter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Electric Meter</label>
        <referenceTo>Electric_Meter__c</referenceTo>
        <relationshipLabel>Electric Transactions</relationshipLabel>
        <relationshipName>Electric_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meter_No__c</fullName>
        <label>Meter No</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Meter_Type__c</fullName>
        <label>Meter Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Meter_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rent_Schedule__c</fullName>
        <label>Rent Schedule</label>
        <referenceTo>Rent_Schedules__c</referenceTo>
        <relationshipLabel>Electric Transactions</relationshipLabel>
        <relationshipName>Electric_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit</label>
        <referenceTo>Units__c</referenceTo>
        <relationshipLabel>Electric Transactions</relationshipLabel>
        <relationshipName>Electric_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Electric Transaction</label>
    <nameField>
        <displayFormat>{yyyy}-{mm}-EC-{00000000}</displayFormat>
        <label>Electric Transactions No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Electric Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WindGroup Dev/src/objects/Rent_Schedules__c.object
<CustomObject>
    <fields>
        <fullName>Charge_Type__c</fullName>
        <description>TEXT(Lease_Charge__r.Charge_Type__c)</description>
        <formula>TEXT(Lease_Charge__r.Charge_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>From Related Lease Charge &gt; Charge Type</inlineHelpText>
        <label>Charge Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Electric_Meter_Number__c</fullName>
        <label>Electric Meter Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Electric_Meter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Electric Meter</label>
        <referenceTo>Electric_Meter__c</referenceTo>
        <relationshipLabel>Rent Schedules</relationshipLabel>
        <relationshipName>Rent_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Remarks__c</fullName>
        <description>This field is created to capture remarks from Ad-Hoc Invoice process</description>
        <label>Remarks</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Vacancy</fullName>
                </value>
                <value>
                    <fullName>In-Tenancy</fullName>
                </value>
                <value>
                    <fullName>No Rent Roll</fullName>
                </value>
                <value>
                    <fullName>Rent Roll Generated</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Rent Free</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Units__c.Property__c</field>
                <operation>equals</operation>
                <valueField>$Source.PropertyLU__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Units__c</referenceTo>
        <relationshipLabel>Rent Schedules</relationshipLabel>
        <relationshipName>Rent_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Rent Schedule</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-RS-{00000000}</displayFormat>
        <label>Rent Schedule No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rent Schedules</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

WindGroup Dev/src/classes/RelinkRentSchedulesController.cls
public class RelinkRentSchedulesController{
    public Electric_Meter__c elecMeter{get;set;}
    public Electric_Meter__c elecMtrUIDt{get;set;}
    public date startDate{get;set;}
    public date endDate{get;set;}
    public Boolean success{get;set;}
    public string oldMeterNo{get;set;}
    public Boolean isError{get;set;}
    public string errorMsg{get;set;}
    public RelinkRentSchedulesController(){
        isError = false;
        success = false;
        //startDate = system.today();
        
        elecMeter = new Electric_Meter__c();
        
        elecMtrUIDt = new Electric_Meter__c();
        elecMtrUIDt.Start_Date__c = system.today();
        
        for(Electric_Meter__c em:[Select id,Meter_No__c,Unit__c,Status__c,Meter_Type__c from Electric_Meter__c where id=:Apexpages.currentPage().getParameters().get('Id')]){
            elecMeter = em;
            oldMeterNo = em.Meter_No__c;
        }
    }
    
    public pageReference save(){
        isError = false;
        errorMsg = '';
        if(elecMeter.Status__c=='Active'){
        	
            if(elecMtrUIDt.Start_Date__c!=null && elecMtrUIDt.End_Date__c!=null){
            	startDate = elecMtrUIDt.Start_Date__c;
            	endDate = elecMtrUIDt.End_Date__c;
                if(startDate<endDate){
                    if(oldMeterNo!=elecMeter.Meter_No__c){
                        List<Rent_Schedules__c> rsList = [Select id,Electric_Meter_Number__c,(Select id from Electric_Transactions__r) from Rent_Schedules__c where Electric_Meter_Number__c like: ('%'+oldMeterNo+'%') and Status__c='In-Tenancy' and ((Start_Date__c>=:startDate and End_Date__c<=:endDate) or (End_Date__c>=:startDate and End_Date__c<=:endDate) or (Start_Date__c<:endDate and End_Date__c>:endDate))];
                        if(rslist.size()>0){
                            for(Rent_Schedules__c rs:rsList){
                                if(rs.Electric_Transactions__r.size()==0){
                                    rs.Electric_Meter_Number__c = rs.Electric_Meter_Number__c.replace(oldMeterNo,elecMeter.Meter_No__c);                                    
                                }
                            }
                            update rsList;
                        }else{
                            rsList = [Select id,Electric_Meter_Number__c,(Select id from Electric_Transactions__r) from Rent_Schedules__c where Charge_Type__c=:elecMeter.Meter_Type__c and  Status__c='In-Tenancy' and ((Start_Date__c>=:startDate and End_Date__c<=:endDate) or (End_Date__c>=:startDate and End_Date__c<=:endDate) or (Start_Date__c<:endDate and End_Date__c>:endDate))];
                            if(rslist.size()>0){
                                for(Rent_Schedules__c rs:rsList){
                                    if(rs.Electric_Transactions__r.size()==0){
                                        if(rs.Electric_Meter_Number__c!=null && rs.Electric_Meter_Number__c.trim().length()>0){
                                            rs.Electric_Meter_Number__c += ';'+elecMeter.Meter_No__c;
                                        }else{
                                            rs.Electric_Meter_Number__c = elecMeter.Meter_No__c;
                                        }
                                        rs.Electric_Meter_Number__c = rs.Electric_Meter_Number__c.replace(oldMeterNo,elecMeter.Meter_No__c);
                                    }
                                }
                                update rsList;
                            }                            
                        }
                        elecMeter.remarks__c = 'Meter No changed from '+oldMeterNo+' to '+elecMeter.Meter_No__c+ ' on '+system.today().day()+'/'+system.today().month()+'/'+system.today().Year();
                    }else{
                        List<Rent_Schedules__c> rsList = [Select id,Electric_Meter_Number__c,(Select id from Electric_Transactions__r) from Rent_Schedules__c where Charge_Type__c=:elecMeter.Meter_Type__c and Status__c='In-Tenancy' and ((Start_Date__c>=:startDate and End_Date__c<=:endDate) or (End_Date__c>=:startDate and End_Date__c<=:endDate) or (Start_Date__c<:endDate and End_Date__c>:endDate))];
                        if(rslist.size()>0){
                            for(Rent_Schedules__c rs:rsList){
                                if(rs.Electric_Transactions__r.size()==0){
                                    if(rs.Electric_Meter_Number__c!=null && rs.Electric_Meter_Number__c.trim().length()>0){
                                        if(!rs.Electric_Meter_Number__c.contains(elecMeter.Meter_No__c)){
                                            rs.Electric_Meter_Number__c += ';'+elecMeter.Meter_No__c;
                                        }
                                    }else{
                                        rs.Electric_Meter_Number__c = elecMeter.Meter_No__c;
                                    }
                                    rs.Electric_Meter_Number__c = rs.Electric_Meter_Number__c.replace(oldMeterNo,elecMeter.Meter_No__c);
                                }
                            }
                            update rsList;
                        }                            
                    }
                }else{
                    isError = true;
                    errorMsg = 'End Date should be greater than Start Date.';
                    return null;
                }
            }else{
                isError = true;
                errorMsg = 'Please enter Start and End Date.';
                return null;
            }
        }else{
            if(oldMeterNo!=elecMeter.Meter_No__c){
                isError = true;
                errorMsg = 'You cannot change Meter No while its Inactive.';
                return null;
            }
            List<Rent_Schedules__c> deleteRsList = new List<Rent_Schedules__c>();
            List<Rent_Schedules__c> updateRsList = new List<Rent_Schedules__c>();
            List<Rent_Schedules__c> rsList = [Select id,Electric_Meter_Number__c,Status__c,(Select id from Electric_Transactions__r) from Rent_Schedules__c where Electric_Meter_Number__c like: ('%'+elecMeter.Meter_No__c+'%') and Status__c='In-Tenancy'];
            if(rsList.size()>0){
                for(Rent_Schedules__c rs:rsList){
                    if(rs.Electric_Transactions__r.size()==0){
                        if(rs.Electric_Meter_Number__c.contains(elecMeter.Meter_No__c+';')){
                            rs.Electric_Meter_Number__c = rs.Electric_Meter_Number__c.replace(elecMeter.Meter_No__c+';','');
                            updateRsList.add(rs);
                        }else if(rs.Electric_Meter_Number__c.contains(';'+elecMeter.Meter_No__c)){
                            rs.Electric_Meter_Number__c = rs.Electric_Meter_Number__c.replace(';'+elecMeter.Meter_No__c,'');
                            updateRsList.add(rs);
                        }else if(rs.Electric_Meter_Number__c==elecMeter.Meter_No__c){
                            deleteRsList.add(rs);
                        }
                    }
                }
                if(updateRsList.size()>0){
                    update updateRsList;
                }
                if(deleteRsList.size()>0){
                    delete deleteRsList;
                }
            }
        }
        update elecMeter;
        success = true;
        return null;
    }
}