WindGroup Dev/src/objects/Lease__c.object
<CustomObject>
    <fields>
        <fullName>Charge_Method__c</fullName>
        <label>Charge Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Charge_Method</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lease_End_Date__c</fullName>
        <formula>IF(ISBLANK(TEXT(Lease_Tenure_Days__c)),0,+ VALUE(TEXT(Lease_Tenure_Days__c))) 
+ 
(DATE( 
YEAR( Lease_Start_Date__c ) + FLOOR( ( MONTH ( Lease_Start_Date__c ) + Lease_Tenure_Mths__c - 1 ) / 12 ), 
MOD( MONTH ( Lease_Start_Date__c ) + Lease_Tenure_Mths__c - 1 + 
IF( DAY ( Lease_Start_Date__c ) &gt; CASE( MOD( MONTH( Lease_Start_Date__c ) + Lease_Tenure_Mths__c - 1, 12 ) + 1, 
2, 28, 
4, 30, 
6, 30, 
9, 30, 
11, 30, 
31 ), 1, 0 ), 12 ) + 1, 
IF( DAY( Lease_Start_Date__c ) &gt; CASE( MOD( MONTH( Lease_Start_Date__c) + Lease_Tenure_Mths__c - 1, 12 ) + 1, 
2, 28, 
4, 30, 
6, 30, 
9, 30, 
11, 30, 
31 ), 
1, DAY( Lease_Start_Date__c ) 
) 
)-1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Original End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lease_Start_Date__c</fullName>
        <label>Lease Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lease_Status__c</fullName>
        <description>Status of the Lease 
New = New sign-up 
Cancelled = Lease is cancelled
Renewed = Lease is renewed 
Expired = Lease has expired with no renewal</description>
        <label>Lease Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Renewed</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Extended</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Pre-Terminated</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lease_Tenure_Days__c</fullName>
        <label>Lease Tenure (Days)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Day</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lease_Tenure_Mths__c</fullName>
        <label>Lease Tenure (Mths)</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Leases</relationshipLabel>
        <relationshipName>Leases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rent_Free_End_Date__c</fullName>
        <label>Rent Free End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Rent_Free_Start_Date__c</fullName>
        <label>Rent Free Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Tenant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tenant</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leases</relationshipLabel>
        <relationshipName>Leases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Lease</label>
    <nameField>
        <label>Lease Agreement No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

WindGroup Dev/src/objects/Lease_POS__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lease_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lease Unit</label>
        <referenceTo>Lease_Unit__c</referenceTo>
        <relationshipLabel>Lease POS</relationshipLabel>
        <relationshipName>Lease_POS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Tenant__c</fullName>
        <formula>Lease_Unit__r.Lease_Agreement_No__r.Tenant__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Tenant</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <formula>Lease_Unit__r.Unit__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unit</label>
        <type>Text</type>
    </fields>
    <label>Lease POS</label>
    <nameField>
        <label>POS ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lease POS</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Shang New Live/src/objects/Lease_POS__c.object
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Lease POS</relationshipLabel>
        <relationshipName>Lease_POS</relationshipName>
        <type>Lookup</type>
    </fields>

WindGroup Dev/src/objects/Lease_Unit__c.object
<CustomObject>
    <fields>
        <fullName>Lease_Agreement_No__c</fullName>
        <label>Lease Agreement No.</label>
        <referenceTo>Lease__c</referenceTo>
        <relationshipLabel>Lease Units</relationshipLabel>
        <relationshipName>Lease_Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Lease_End_Date__c</fullName>
        <description>FLS should be Read-Only for all Users</description>
        <inlineHelpText>Lease End Date
This is updated via Pre-Termination and Extension process and further related influence LC and RS.</inlineHelpText>
        <label>Lease End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lease_Start_Date__c</fullName>
        <label>Lease Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <formula>Unit__r.Level__r.Name</formula>
        <label>Level</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <formula>Lease_Agreement_No__r.Property__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Property</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rent_Free_End_Date__c</fullName>
        <label>Rent Free End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Rent_Free_Start_Date__c</fullName>
        <label>Rent Free Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Tenant__c</fullName>
        <formula>if(Lease_Agreement_No__r.Tenant__c != null , Lease_Agreement_No__r.Tenant__r.Name, &apos;&apos;)</formula>
        <label>Tenant</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Units__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Units__c</referenceTo>
        <relationshipLabel>Lease Units</relationshipLabel>
        <relationshipName>Lease_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Lease Unit</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-LU-{00000000}</displayFormat>
        <label>Lease Unit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lease Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Shang New Live/src/objects/Lease_Unit__c.object
    <fields>
        <fullName>Lease_Status__c</fullName>
        <label>Lease Unit Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Renewed</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Pre-Terminated</fullName>
                </value>
                <value>
                    <fullName>Extended</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Replaced</fullName>
                </value>
                <value>
                    <fullName>Vacant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

WindGroup Dev/src/objects/Level__c.object
<CustomObject>
    <fields>
        <fullName>NLA_SQF__c</fullName>
        <label>NLA (SQF)</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Levels</relationshipLabel>
        <relationshipName>Levels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Level</label>
    <nameField>
        <label>Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Levels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WindGroup Dev/src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NLA_SQF__c</fullName>
        <label>NLA (SQF)</label>
        <summarizedField>Units__c.NLA_SQF__c</summarizedField>
        <summaryForeignKey>Units__c.Property__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Short_Code__c</fullName>
        <externalId>true</externalId>
        <label>Short Code</label>
        <length>5</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

WindGroup Dev/src/objects/Units__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Charge_Method__c</fullName>
        <inlineHelpText>Transaction Rate is not applicable for Unit.</inlineHelpText>
        <label>Charge Method</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Charge_Method</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Level</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Property__c</field>
                <operation>equals</operation>
                <valueField>Level__c.Property__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Level__c</referenceTo>
        <relationshipLabel>Units</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NLA_SQF__c</fullName>
        <label>NLA (SQF)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Units</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Unit_No__c</fullName>
        <formula>&quot;#&quot;&amp; TEXT( Floor__c ) &amp;&quot;-&quot;&amp; IF( ISPICKVAL(  Space_Type__c  , &quot;ATM&quot;) , &quot;A&quot;, 
IF(ISPICKVAL(  Space_Type__c  , &quot;Storage&quot;), &quot;S&quot;, IF(ISPICKVAL (  Space_Type__c , &quot;Counter&quot;) , &quot;C&quot;, &quot;&quot;)) )&amp; No__c</formula>
        <label>Unit No.</label>
        <type>Text</type>
    </fields>
    <label>Unit</label>
    <nameField>
        <label>Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WindGroup Dev/src/classes/NewLeasePOSRedirectControllertest.cls
@istest
public class NewLeasePOSRedirectControllertest {
    static testmethod void testNewLeasePOSRedirectController(){
    
     Account ac=new Account();
        ac.Name='TestAc';
        insert ac;
        
        Property__c Prop=new Property__c();
        prop.name='testProp';
        prop.Short_Code__c='abc';
        insert prop;
        
        Lease__c l=new Lease__c();
        l.Tenant__c=ac.Id;
        l.Rent_Free_Start_Date__c=date.today();
        l.Rent_Free_End_Date__c=date.today()+5;
        
        l.Property__c=prop.Id;
        l.Lease_Start_Date__c=date.today();
        l.Lease_Tenure_Mths__c=10;
        l.Lease_Tenure_Days__c='5';
        l.Lease_Status__c='new';
        insert l;
        
        
          
        Level__c le = new Level__c();
        le.Name = 'abc';
        le.Property__c = prop.id;
        insert le;
        
        Units__c un = new Units__c();
        un.Property__c =prop.id;
        un.Level__c = le.id;
        //un.Unit_No__c ='123';
         un.Active__c =true;
        un.NLA_SQF__c =1.0;
        un.Charge_Method__c = 'daily rate';
        un.Start_Date__c =date.today();
        un.End_Date__c = date.today()+5;
        insert un;
        
        Lease__c ls = new Lease__c();
        ls.Tenant__c = ac.id;
        ls.Property__c =prop.id;
        ls.Lease_Start_Date__c =date.today()+5;
        ls.Lease_Tenure_Mths__c = 12;
        ls.Lease_Tenure_Days__c ='18';
        ls.Lease_Status__c ='New';
        insert ls;
        
       
        
        Lease_Unit__c lu = new Lease_Unit__c();
        lu.Lease_Agreement_No__c =ls.id;
        lu.Unit__c = un.id;
        lu.Lease_Start_Date__c =date.today();
          lu.Lease_End_Date__c =date.today() + 1;
        insert lu;
        
        
         Lease_POS__c lp = new Lease_POS__c();
        lp.Lease_Unit__c = lu.id;
        try{
        insert lp;
        }catch(exception e){}
        
        
        ApexPages.StandardController sc = new ApexPages.StandardController(lp);
        NewLeasePOSRedirectController testAccPlan = new NewLeasePOSRedirectController(sc);
        
}   
}