WindGroup Dev/src/objects/Lease_Plan__c.object
<CustomObject>
    <description>Used to capture Status of a Unit (Vacant, Committed, LOI)
Managed by Unit creation, LOI process, Lease Unit</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LOI_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LOI Unit</label>
        <referenceTo>LOI_Unit__c</referenceTo>
        <relationshipLabel>Lease Plans</relationshipLabel>
        <relationshipName>Lease_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LOI__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LOI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <formula>Unit__r.Property__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Property</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit</label>
        <referenceTo>Units__c</referenceTo>
        <relationshipLabel>Lease Plans</relationshipLabel>
        <relationshipName>Lease_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Lease Plan</label>
    <nameField>
        <displayFormat>{YYYYMM}-LP-{000000}</displayFormat>
        <label>Lease Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lease Plans</pluralLabel>
    <recordTypes>
        <fullName>Monthly</fullName>
        <active>true</active>
        <label>Monthly</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WindGroup Dev/src/objects/Level__c.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Levels</relationshipLabel>
        <relationshipName>Levels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Level</label>
    <nameField>
        <label>Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Levels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WindGroup Dev/src/objects/LOI__c.object
<CustomObject>
    <fields>
        <fullName>Charge_Method__c</fullName>
        <description>managed by Global Picklist</description>
        <label>Charge Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Charge_Method</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>LOI_End_Date__c</fullName>
        <formula>IF(ISBLANK(TEXT(LOI_Tenure_Days__c)),0,+ VALUE(TEXT(LOI_Tenure_Days__c))) 
+ 
(DATE( 
YEAR( LOI_Start_Date__c ) + FLOOR( ( MONTH ( LOI_Start_Date__c ) + LOI_Tenure_Mths__c - 1 ) / 12 ), 
MOD( MONTH ( LOI_Start_Date__c ) + LOI_Tenure_Mths__c - 1 + 
IF( DAY ( LOI_Start_Date__c ) &gt; CASE( MOD( MONTH( LOI_Start_Date__c ) + LOI_Tenure_Mths__c - 1, 12 ) + 1, 
2, 28, 
4, 30, 
6, 30, 
9, 30, 
11, 30, 
31 ), 1, 0 ), 12 ) + 1, 
IF( DAY( LOI_Start_Date__c ) &gt; CASE( MOD( MONTH( LOI_Start_Date__c) + LOI_Tenure_Mths__c - 1, 12 ) + 1, 
2, 28, 
4, 30, 
6, 30, 
9, 30, 
11, 30, 
31 ), 
1, DAY( LOI_Start_Date__c ) 
) 
)-1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Original End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LOI_Start_Date__c</fullName>
        <label>LOI Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>LOIs</relationshipLabel>
        <relationshipName>LOIs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tenant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tenant</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>LOIs</relationshipLabel>
        <relationshipName>LOIs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>LOI</label>
    <nameField>
        <label>LOI Agreement No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LOIs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

WindGroup Dev/src/objects/LOI_Unit__c.object
<CustomObject>
    <fields>
        <fullName>LOI_Agreement_No__c</fullName>
        <label>LOI Agreement No.</label>
        <referenceTo>LOI__c</referenceTo>
        <relationshipLabel>LOI Units</relationshipLabel>
        <relationshipName>LOI_Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LOI_End_Date__c</fullName>
        <label>LOI End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LOI_Start_Date__c</fullName>
        <label>LOI Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <formula>Unit__r.Level__r.Name</formula>
        <label>Level</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <formula>LOI_Agreement_No__r.Property__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Property</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tenant__c</fullName>
        <formula>if( LOI_Agreement_No__r.Tenant__c != null,  LOI_Agreement_No__r.Tenant__r.Name, &apos;&apos;)</formula>
        <label>Tenant</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit</label>
        <referenceTo>Units__c</referenceTo>
        <relationshipLabel>LOI Units</relationshipLabel>
        <relationshipName>LOI_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Update_LOI_Plans__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Update LOI Plans</label>
        <type>Checkbox</type>
    </fields>
    <label>LOI Unit</label>
    <nameField>
        <label>LOI Unit No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LOI Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WindGroup Dev/src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

WindGroup Dev/src/objects/Units__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Charge_Method__c</fullName>
        <inlineHelpText>Transaction Rate is not applicable for Unit.</inlineHelpText>
        <label>Charge Method</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Charge_Method</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Generate_Lease_Plans__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Generate Lease Plans</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Level</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Property__c</field>
                <operation>equals</operation>
                <valueField>Level__c.Property__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Level__c</referenceTo>
        <relationshipLabel>Units</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Units</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Unit</label>
    <nameField>
        <label>Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WindGroup Dev/src/classes/MainLOIUnitTrigger_Test.cls
@isTest(seeAllData=false)
public with sharing class MainLOIUnitTrigger_Test {
   static Property__c prop;
   static Units__c unt;
   static LOI_Unit__c lu;
   static LOI_Unit__c lu2;
    static void init(){
         prop = new Property__c();
        prop.Name = 'TestProperty';
        insert prop;
        
        Level__c lvl = new Level__c();
        lvl.Name = 'TestLevel';
        lvl.Property__c = prop.Id;
        insert lvl;
        
        unt = new Units__c();
        unt.Property__c = prop.Id;
        unt.Level__c = lvl.Id;
        unt.Name = 'TestUnit';
        unt.Generate_Lease_Plans__c = true;
        unt.Active__c = true;
        unt.Start_Date__c = system.today();
        unt.End_Date__c = system.today().addYears(1);
        unt.Charge_Method__c = 'Monthly Rate - CL';
        insert unt;
        
        Account acc = new Account();
        acc.Name = 'TestTenant';
        insert acc;
        
        LOI__c ls = new LOI__c();
        ls.Tenant__c = acc.Id;
        ls.Property__c = prop.Id;        
        insert ls;
        
        Lease_Plan__c lp = new Lease_Plan__c();
        lp.Unit__c = unt.Id;
        lp.Start_Date__c = unt.Start_Date__c;
        lp.End_Date__c = Date.newInstance(unt.Start_Date__c.year(),unt.Start_Date__c.month(),Date.DaysInMonth(unt.Start_Date__c.Year(),unt.Start_Date__c.Month()));
        for(Date dts=unt.Start_Date__c;dts<=lp.End_Date__c; dts = dts+1){
            lp.put('Daily_Rate_'+dts.Day()+'__c',dts.day());
            
            if(dts.Day() > 0 && dts.Day() < 7){
                lp.put('Status_'+dts.Day()+'__c','Committed');
            }else if(dts.Day() > 7 && dts.Day() < 15){
                lp.put('Status_'+dts.Day()+'__c','Vacant');
            }else if(dts.Day() > 17 && dts.Day() < 25){
                lp.put('Status_'+dts.Day()+'__c','LOI');
            }
        }
        insert lp;
        
        lu = new LOI_Unit__c();
        lu.LOI_Agreement_No__c = ls.Id;
        lu.Unit__c = unt.Id;
        lu.LOI_Start_Date__c = unt.Start_Date__c+2;
        lu.LOI_End_Date__c = lu.LOI_Start_Date__c+3;
        lu.Update_LOI_Plans__c = true;
        
        lu2 = new LOI_Unit__c();
        lu2.LOI_Agreement_No__c = ls.Id;
        lu2.Unit__c = unt.Id;
        lu2.LOI_Start_Date__c = lu.LOI_End_Date__c+30;
        lu2.LOI_End_Date__c = lu2.LOI_Start_Date__c+5;
        insert lu2;
        
        
    }
     static testMethod void Test(){
         init();
         Test.startTest();
         insert lu;
         
         Test.stopTest();
     }
       static testMethod void Test1(){
         init();
         Test.startTest();
         lu2.Update_LOI_Plans__c = true;
         update lu2;
         Test.stopTest();
     }      
}