WindGroup Dev/src/objects/Lease__c.object
<CustomObject>
    <fields>
        <fullName>Lease_End_Date__c</fullName>
        <formula>IF(ISBLANK(TEXT(Lease_Tenure_Days__c)),0,+ VALUE(TEXT(Lease_Tenure_Days__c))) 
+ 
(DATE( 
YEAR( Lease_Start_Date__c ) + FLOOR( ( MONTH ( Lease_Start_Date__c ) + Lease_Tenure_Mths__c - 1 ) / 12 ), 
MOD( MONTH ( Lease_Start_Date__c ) + Lease_Tenure_Mths__c - 1 + 
IF( DAY ( Lease_Start_Date__c ) &gt; CASE( MOD( MONTH( Lease_Start_Date__c ) + Lease_Tenure_Mths__c - 1, 12 ) + 1, 
2, 28, 
4, 30, 
6, 30, 
9, 30, 
11, 30, 
31 ), 1, 0 ), 12 ) + 1, 
IF( DAY( Lease_Start_Date__c ) &gt; CASE( MOD( MONTH( Lease_Start_Date__c) + Lease_Tenure_Mths__c - 1, 12 ) + 1, 
2, 28, 
4, 30, 
6, 30, 
9, 30, 
11, 30, 
31 ), 
1, DAY( Lease_Start_Date__c ) 
) 
)-1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Original End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lease_Start_Date__c</fullName>
        <label>Lease Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Original_End_Date__c</fullName>
        <inlineHelpText>This field would be populated only in the case of Extension or Pre-Termination and would show the Revised End Date as per Extension or Pre-Termination.</inlineHelpText>
        <label>Revised End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reason_for_Termination__c</fullName>
        <label>Reason for Termination</label>
        <type>TextArea</type>
    </fields>
    <label>Lease</label>
    <nameField>
        <label>Lease Agreement No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

WindGroup Dev/src/objects/Lease_Charges__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lease_Unit__c</fullName>
        <label>Lease Unit</label>
        <referenceTo>Lease_Unit__c</referenceTo>
        <relationshipName>Lease_Charges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Pre_Termination__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pre-Termination</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Lease Charge</label>
    <nameField>
        <label>Lease Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lease Charges</pluralLabel>
    <recordTypes>
        <fullName>Rent</fullName>
        <active>true</active>
        <description>Base Rent &amp; GTO</description>
        <label>Rent</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WindGroup Dev/src/objects/Lease_POS__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lease_POS__c</fullName>
        <label>Application Id</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>POS-01</fullName>
                </value>
                <value>
                    <fullName>POS-01D</fullName>
                </value>
                <value>
                    <fullName>POS-01M</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lease_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lease Unit</label>
        <referenceTo>Lease_Unit__c</referenceTo>
        <relationshipLabel>Lease POS</relationshipLabel>
        <relationshipName>Lease_POS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Status</valueSetName>
        </valueSet>
    </fields>
    <label>Lease POS</label>
    <nameField>
        <label>POS ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lease POS</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

WindGroup Dev/src/objects/Lease_Unit__c.object
<CustomObject>
    <fields>
        <fullName>Lease_Agreement_No__c</fullName>
        <label>Lease Agreement No.</label>
        <referenceTo>Lease__c</referenceTo>
        <relationshipLabel>Lease Units</relationshipLabel>
        <relationshipName>Lease_Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Lease_End_Date__c</fullName>
        <description>FLS should be Read-Only for all Users</description>
        <inlineHelpText>Lease End Date
This is updated via Pre-Termination and Extension process and further related influence LC and RS.</inlineHelpText>
        <label>Lease End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lease_Start_Date__c</fullName>
        <label>Lease Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Original_End_Date__c</fullName>
        <inlineHelpText>This field would be populated only in the case of Extension or Pre-Termination and would show the Original End Date of this Lease Unit.</inlineHelpText>
        <label>Original End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Pre_Termination__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pre-Terminated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reason_for_Termination__c</fullName>
        <label>Reason for Terminated</label>
        <type>TextArea</type>
    </fields>
    <label>Lease Unit</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-LU-{00000000}</displayFormat>
        <label>Lease Unit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lease Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WindGroup Dev/src/objects/Rent_Schedules__c.object
<CustomObject>
    <fields>
        <fullName>Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lease_Agreement_No__c</fullName>
        <formula>Lease_Unit__r.Lease_Agreement_No__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>from related Lease Unit</inlineHelpText>
        <label>Lease Agreement No.</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lease_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lease Unit</label>
        <referenceTo>Lease_Unit__c</referenceTo>
        <relationshipLabel>Rent Schedules</relationshipLabel>
        <relationshipName>Rent_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Vacancy</fullName>
                </value>
                <value>
                    <fullName>In-Tenancy</fullName>
                </value>
                <value>
                    <fullName>No Rent Roll</fullName>
                </value>
                <value>
                    <fullName>Rent Roll Generated</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Rent Free</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Rent Schedule</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-RS-{00000000}</displayFormat>
        <label>Rent Schedule No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rent Schedules</pluralLabel>
    <recordTypes>
        <fullName>Rent</fullName>
        <active>true</active>
        <description>Base Rent &amp; GTO</description>
        <label>Rent</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

WindGroup Dev/src/classes/PreTerminateLU_Extension.cls
public  class PreTerminateLU_Extension {
    public Lease_Unit__c lu{get;set;}
    public Boolean termError{get;set;}
    public Boolean error{get;set;}
    public Boolean closePage{get;set;}
    public String dtString{get;set;}
    public String selectedLU{get;set;}
    String currentEndDate{get;set;}
    Date EndDate{get;set;}
    public PreTerminateLU_Extension(ApexPages.StandardController stdController) {
        this.lu = (Lease_Unit__c) stdController.getRecord();
        lu.Lease_End_Date__c = System.today();
        currentEndDate = ApexPages.currentpage().getParameters().get('endDate');
        selectedLU = ApexPages.currentpage().getParameters().get('selectedLeaseUnits');

        if (currentEndDate != null && currentEndDate != '') {
            EndDate = date.parse(currentEndDate);
        }
        error = true;
    }

    public void checkDate() {
    	SavePoint sp = Database.setSavePoint();
        error = false;
        termError = false;

        Lease_Unit__c leaseUnit = [Select Id, Name,Pre_Termination__c, Original_End_Date__c, Lease_Start_Date__c, Lease_End_Date__c, Lease_Agreement_No__r.Lease_Start_Date__c, Lease_Agreement_No__r.Lease_End_Date__c from Lease_Unit__c where Id =: selectedLU];

        if (lu.Reason_for_Termination__c == null || lu.Reason_for_Termination__c.trim() == '') {
            termError = true;
            error = true;
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, 'Please add Reason for Termination'));
        }

        if (lu.Lease_End_Date__c == null) {
            error = true;
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, 'Please Select Termination Date.'));
        } else if (lu.Lease_End_Date__c <= leaseUnit.Lease_Start_Date__c) {
            error = true;
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, 'Termination Date must be after Lease Unit Start Date'));
        } else if (lu.Lease_End_Date__c > leaseUnit.Lease_End_Date__c) {
            error = true;
            if (lu.Lease_End_Date__c > leaseUnit.Lease_End_Date__c) {
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, 'Termination Date must be before Lease Unit End Date'));
            } else {
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, 'Termination Date must be before Lease Unit Original End Date'));
            }
        } else {
            error = false;
            dtString = DateTime.newInstance(lu.Lease_End_Date__c.year(), lu.Lease_End_Date__c.month(), lu.Lease_End_Date__c.day()).format('YYYY/MM/d');
        }

        if (!error && !termError) {

            if (leaseUnit != null || Test.isRunningTest()) {
                closePage = true;
                leaseunit.Pre_Termination__c = true;
                leaseUnit.Reason_for_Termination__c = lu.Reason_for_Termination__c;
                leaseUnit.Lease_Start_Date__c = lu.Lease_Agreement_No__r.Lease_Start_Date__c;
                if (leaseUnit.Original_End_Date__c == null) {
                    leaseUnit.Original_End_Date__c = leaseUnit.Lease_End_Date__c;
                }
                leaseUnit.Lease_End_Date__c = lu.Lease_End_Date__c;
                
                List<Lease_POS__c> posList = [select Id, End_Date__c, Start_Date__c, Status__c from Lease_POS__c where Lease_Unit__c =: selectedLU And (Start_Date__c >=: lu.Lease_End_Date__c or End_Date__c >=: lu.Lease_End_Date__c)];
                for(Lease_POS__c lpos:posList){
                	lpos.Start_Date__c = (lpos.Start_Date__c > lu.Lease_End_Date__c)?lu.Lease_End_Date__c:lpos.Start_Date__c;
                	lpos.End_Date__c = lu.Lease_End_Date__c;
                }
                    List < Rent_Schedules__c > rsList = [Select Id, Status__c, Start_Date__c, End_Date__c, Lease_Unit__c, Lease_Unit__r.Lease_Start_Date__c, Lease_Unit__r.Lease_End_Date__c from Rent_Schedules__c where Lease_Unit__c =: selectedLU];
                    if (rsList.size() > 0) {
                        for (Rent_Schedules__c rs: rsList) {
                            if(rs.Status__c == 'Rent Roll Generated' && rs.Start_Date__c >= lu.Lease_End_Date__c && rs.End_Date__c >= lu.Lease_End_Date__c){
                            	error = true;
                            	closePage = false;
    							ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'Rent Roll already generated for this Lease Unit and cannot be Terminated.'));
                            }else if (rs.Start_Date__c > lu.Lease_End_Date__c) {
                                rs.Status__c = 'Terminated';
                                rs.Approved__c = true;
                            } else if (rs.Start_Date__c < lu.Lease_End_Date__c && rs.End_Date__c > lu.Lease_End_Date__c) {
                                rs.End_Date__c = lu.Lease_End_Date__c;
                            }
                        }
                        
                    }

                    List< Lease_Charges__c > lcList = [Select Id,Pre_Termination__c, Start_Date__c, End_Date__c, Lease_Unit__c, Lease_Unit__r.Lease_Start_Date__c, Lease_Unit__r.Lease_End_Date__c from Lease_Charges__c where Lease_Unit__c =: selectedLU];
                    if (lcList.size() > 0) {
                        for (Lease_Charges__c lcl: lcList) {
                        	lcl.Pre_Termination__c = true;
                            if (lcl.End_Date__c > lu.Lease_End_Date__c && lcl.Start_Date__c < lu.Lease_End_Date__c) {
                                lcl.End_Date__c = lu.Lease_End_Date__c;
                            }
                        }
                        
                    }
                if(!error)
	                try {
	                	update leaseUnit;
	                	update posList;
	                	//update rsList; removed because RS is terminated from LC via Trigger. here rsList is used just for validation
	                	update lcList;
	                } catch (Exception e) {
	                	Database.rollback(sp);
	                    closePage = false;
	                    error = true;
	                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, 'Exception Occured- ' + e));
	                }
            }
        }
    }
}