WindGroup Dev/src/objects/Lease_Charges__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Parent_Lease_Charge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Applicable for Discount Cases.
Use this Lookup ref for Discount LC only.</inlineHelpText>
        <label>Parent Lease Charge</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Lease_Charges__c.Lease_Unit__c</field>
                <operation>equals</operation>
                <valueField>$Source.Lease_Unit__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Lease_Charges__c</referenceTo>
        <relationshipLabel>Lease Charges (Discount)</relationshipLabel>
        <relationshipName>Lease_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pre_Termination__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pre-Termination</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Lease Charge</label>
    <nameField>
        <label>Lease Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lease Charges</pluralLabel>
    <recordTypes>
        <fullName>Rent</fullName>
        <active>true</active>
        <description>Base Rent &amp; GTO</description>
        <label>Rent</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WindGroup Dev/src/objects/Rent_Schedules__c.object
<CustomObject>
    <fields>
        <fullName>Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lease_Charge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lease Charge</label>
        <referenceTo>Lease_Charges__c</referenceTo>
        <relationshipLabel>Rent Schedules</relationshipLabel>
        <relationshipName>Rent_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Vacancy</fullName>
                </value>
                <value>
                    <fullName>In-Tenancy</fullName>
                </value>
                <value>
                    <fullName>No Rent Roll</fullName>
                </value>
                <value>
                    <fullName>Rent Roll Generated</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Rent Free</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Rent Schedule</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-RS-{00000000}</displayFormat>
        <label>Rent Schedule No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rent Schedules</pluralLabel>
    <recordTypes>
        <fullName>Rent</fullName>
        <active>true</active>
        <description>Base Rent &amp; GTO</description>
        <label>Rent</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

WindGroup Dev/src/classes/PreTerminateLC_Extension.cls
public  class PreTerminateLC_Extension {
	public Lease_Charges__c leaseCharge{get;set;}
    public String selectedLeaseCharge{get;set;}
    public Boolean closePage{get;set;}
	public Boolean error{get;set;}
    public Boolean termError{get;set;}
    public String dtString{get;set;}
    String currentEndDate{get;set;}
    Date EndDate{get;set;}
    public Boolean erroOnLoad{get;set;}
    public PreTerminateLC_Extension(ApexPages.StandardController stdController) {
        this.leaseCharge = (Lease_Charges__c)stdController.getRecord();
        selectedLeaseCharge =  ApexPages.currentpage().getParameters().get('selectedLeaseCharges');
        currentEndDate =   ApexPages.currentpage().getParameters().get('endDate'); 
        
        leaseCharge.End_Date__c = date.parse(currentEndDate);
        
        
        list<Lease_Charges__c> discLClist = [select Id,Parent_Lease_Charge__c,Pre_Termination__c from Lease_Charges__c where Parent_Lease_Charge__c =: selectedLeaseCharge And Pre_Termination__c = false];
        System.debug('discLClist-->'+discLClist);
        if(discLClist.size()>0){
        	erroOnLoad =true;
        	ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'Please Terminate dependent Lease Charge and related Rent Schedule(s) before you proceed.')); 
        }
    }
    public void  checkDate() {
    	SavePoint sp = Database.setSavePoint();
		error = false;
		
		Lease_Charges__c lcTerminate = [select Id, Pre_Termination__c	,Start_Date__c, End_Date__c from Lease_Charges__c where id =: selectedLeaseCharge];
		
		if(leaseCharge.End_Date__c == null){
    		error = true;
    		ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'Please Select Termination Date.'));
    	}else if( leaseCharge.End_Date__c < lcTerminate.Start_Date__c){
    		error = true;
    		ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'Termination Date must be after Lease Charge Start Date'));
    	}else if(leaseCharge.End_Date__c > lcTerminate.End_Date__c ){
    		error = true;
			ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'Termination Date must be before Lease Charge End Date'));
    	}else{
    		error = false;
    		dtString = DateTime.newInstance(leaseCharge.End_Date__c.year(),leaseCharge.End_Date__c.month(),leaseCharge.End_Date__c.day()).format('YYYY/MM/d');
    	}
    	if(!error){
    		if(leaseCharge != null || Test.isRunningTest()){
    			closePage = true;
    			lcTerminate.End_Date__c =  leaseCharge.End_Date__c;
    			lcTerminate.Pre_Termination__c	 = true;
    			
    			List<Rent_Schedules__c> rsList=[Select Id,Status__c,Start_Date__c, End_Date__c, Lease_Charge__c, Lease_Charge__r.Start_Date__c, Lease_Charge__r.End_Date__c from Rent_Schedules__c where Lease_Charge__c =:lcTerminate.Id];
    			if(rsList.size() > 0){
    				for(Rent_Schedules__c rs: rsList){ 
    					if(rs.Status__c == 'Rent Roll Generated' && rs.Start_Date__c >= leaseCharge.End_Date__c && rs.End_Date__c >= leaseCharge.End_Date__c){
    							error = true;
    							closePage = false;
    							ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'Rent Roll already generated for this Lease Charge and cannot be Terminated.'));
    					}else{
    						if(rs.Start_Date__c > leaseCharge.End_Date__c){
	    						rs.Status__c = 'Terminated';
			                    rs.Approved__c = true;
	    					}else if(rs.Start_Date__c < leaseCharge.End_Date__c && rs.End_Date__c > leaseCharge.End_Date__c){
	    						rs.End_Date__c = leaseCharge.End_Date__c;
	    					}
    					}
    				}
    			}
    			if(!error)
	    			try{
						update lcTerminate;
						//update rsList; removed because RS is terminated from LC via Trigger. here rsList is used just for validation
		            }catch(Exception e){
		            	Database.rollback(sp);
		            	closePage = false;
		            	error = true;
		            	ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'Exception Occured- '+e));
		            }
    		}
    	}
    	
    }
}